name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Build
        run: |
          yarn
          yarn build
          yarn copy-seo
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: build
          path: build
