name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/build
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      - run: cat ./build/index.html
